name: Swarm Diagnostics & Cleanup

on:
  workflow_dispatch:

jobs:
  diagnose:
    name: Run Swarm Diagnostics & Cleanup
    runs-on: self-hosted
    steps:
      - name: Swarm Status Before Clean
        run: |
          set -x
          docker info --format 'Swarm State: {{.Swarm.LocalNodeState}} | Manager: {{.Swarm.ControlAvailable}}'
          docker stack ls || true
          docker stack ps madeena-iam --no-trunc || true
          docker service logs madeena-iam_app --tail=100 || true
          docker service logs madeena-iam_queue --tail=100 || true
          docker service logs madeena-iam_db --tail=100 || true
          docker service logs madeena-iam_nginx --tail=100 || true

      - name: Swarm Clean
        run: |
          set -x
          docker stack rm madeena-iam || true
          echo "Waiting for services and network to be removed..."
          sleep 15

      - name: Swarm Status After Clean
        run: |
          set -x
          docker stack ls || true
          docker network ls || true
